apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-registry
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ai-registry.lb.djnd.si
        - registerui.djnd.si
        - registerui.danesjenovdan.si
      secretName: ai-registry-tls
  rules:
    - host: ai-registry.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-registry
                port:
                  number: 8000
    - host: registerui.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-registry
                port:
                  number: 8000
    - host: registerui.danesjenovdan.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-registry
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-registry-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.ai-registry.lb.djnd.si
      secretName: ai-registry-nginx-tls
  rules:
    - host: files.ai-registry.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-registry-nginx
                port:
                  number: 80
