apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-registry
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ai-registry
    newName: rg.fr-par.scw.cloud/djnd/ai-registry
    newTag: 'e326e8111482e4865750a1819bd9f35b565588ee'
