# Generated by Django 5.1.1 on 2024-10-04 13:03

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registryentry",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene z vejico",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Oznake",
            ),
        ),
    ]
