# Generated by Django 5.1.1 on 2024-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_registryentry_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registryentry",
            name="data_sources",
        ),
    ]
