# Generated by Django 5.1.1 on 2024-10-11 11:22

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0003_remove_registryentry_data_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Področje",
                "verbose_name_plural": "Področja",
            },
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="area",
        ),
        migrations.CreateModel(
            name="TaggedArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="home.areatag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oznaka področja",
                "verbose_name_plural": "Oznake področij",
            },
        ),
        migrations.AddField(
            model_name="registryentry",
            name="areas",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločena z vejico",
                through="home.TaggedArea",
                to="home.AreaTag",
                verbose_name="Področja",
            ),
        ),
    ]
