# Generated by Django 5.1.1 on 2024-10-14 16:50

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0004_areatag_remove_registryentry_area_taggedarea_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oznaka",
                "verbose_name_plural": "Oznake",
            },
        ),
        migrations.CreateModel(
            name="TaggedGeneric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="home.generictag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oznaka",
                "verbose_name_plural": "Oznake",
            },
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene z vejico",
                through="home.TaggedGeneric",
                to="home.GenericTag",
                verbose_name="Oznake",
            ),
        ),
    ]
