# Generated by Django 5.1.1 on 2024-10-14 18:22

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0005_generictag_taggedgeneric_alter_registryentry_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institucija",
                "verbose_name_plural": "Institucije",
            },
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="institution",
        ),
        migrations.CreateModel(
            name="TaggedInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="home.institutiontag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oznaka institucije",
                "verbose_name_plural": "Oznake institucij",
            },
        ),
        migrations.AddField(
            model_name="registryentry",
            name="institutions",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene z vejico",
                through="home.TaggedInstitution",
                to="home.InstitutionTag",
                verbose_name="Institucije",
            ),
        ),
    ]
