# Generated by Django 5.1.1 on 2024-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_institutiontag_remove_registryentry_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Datoteka"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Povezava"),
        ),
    ]
