# Generated by Django 5.1.1 on 2024-11-14 09:53

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_link_file_alter_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="registryentry",
            name="license_duration_comment",
            field=models.TextField(
                blank=True, verbose_name="Komentarji o trajanju licence"
            ),
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="areas",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločena s podpičjem",
                through="home.TaggedArea",
                to="home.AreaTag",
                verbose_name="Področja",
            ),
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="institutions",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene s podpičjem",
                through="home.TaggedInstitution",
                to="home.InstitutionTag",
                verbose_name="Institucije",
            ),
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene s podpičjem",
                through="home.TaggedGeneric",
                to="home.GenericTag",
                verbose_name="Oznake",
            ),
        ),
    ]
