# Generated by Django 5.1.1 on 2024-12-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_registryentry_license_duration_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registryentry",
            name="time_in_use_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Obdobje rabe (uporabljeno za razvrščanje)",
            ),
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="time_in_use",
            field=models.CharField(
                blank=True,
                max_length=30,
                verbose_name="Obdobje rabe (uporabljeno za prikaz)",
            ),
        ),
    ]
