# Generated by Django 5.1.1 on 2025-07-31 09:32

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("home", "0009_registryentry_time_in_use_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registryentry",
            name="public_procurement",
            field=models.BooleanField(
                default=False,
                help_text="Ali je bil vnos predmet javnega naročila?",
                verbose_name="Javno naročilo",
            ),
        ),
        migrations.AddField(
            model_name="registryentry",
            name="public_procurement_date",
            field=models.DateField(
                blank=True,
                help_text="Datum objave javnega naročila, če je predmet javnega naročila",
                null=True,
                verbose_name="Datum objave javnega naročila",
            ),
        ),
        migrations.AddField(
            model_name="registryentry",
            name="public_procurement_number",
            field=models.CharField(
                blank=True,
                help_text="Številka javnega naročila, če je predmet javnega naročila",
                max_length=50,
                null=True,
                verbose_name="Številka javnega naročila",
            ),
        ),
        migrations.AddField(
            model_name="registryentry",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Ali je vnos v register objavljen?",
                verbose_name="Objavljeno",
            ),
        ),
        migrations.CreateModel(
            name="TaggedContractingInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="home.institutiontag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oznaka institucije",
                "verbose_name_plural": "Oznake institucij",
            },
        ),
        migrations.AddField(
            model_name="registryentry",
            name="contracting_institution",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Ločene s podpičjem",
                through="home.TaggedContractingInstitution",
                to="home.InstitutionTag",
                verbose_name="Naročnik",
            ),
        ),
    ]
