# Generated by Django 5.2.8 on 2025-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_registryentry_public_procurement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registryentry",
            name="public_procurement_number_eu",
            field=models.CharField(
                blank=True,
                help_text="Številka javnega naročila na portalu TED (tenders electronic daily), če je predmet javnega naročila",
                max_length=50,
                null=True,
                verbose_name="Številka objave na TED",
            ),
        ),
        migrations.AlterField(
            model_name="registryentry",
            name="public_procurement_number",
            field=models.CharField(
                blank=True,
                help_text="Številka javnega naročila na portalu javnih naročil (PJN), če je predmet javnega naročila",
                max_length=50,
                null=True,
                verbose_name="Številka objave na PJN",
            ),
        ),
    ]
