# Generated by Django 5.2.8 on 2025-11-11 10:35

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_registryentry_public_procurement_number_eu_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="registy_entry",
            new_name="registry_entry",
        ),
        migrations.CreateModel(
            name="RegistryEntryInstitutionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost",
                    models.CharField(blank=True, max_length=50, verbose_name="Cena"),
                ),
                (
                    "cost_comment",
                    models.TextField(blank=True, verbose_name="Komentarji o ceni"),
                ),
                (
                    "license_duration",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Trajanje licence (če kupljeno)",
                    ),
                ),
                (
                    "license_duration_comment",
                    models.TextField(
                        blank=True, verbose_name="Komentarji o trajanju licence"
                    ),
                ),
                (
                    "human_rights_analysis_done",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analiza učinka na človekove pravice opravljena",
                    ),
                ),
                (
                    "human_rights_analysis_comments",
                    models.TextField(
                        blank=True,
                        verbose_name="Komentarji analize učinka na človekove pravice",
                    ),
                ),
                (
                    "personal_data_analysis_done",
                    models.BooleanField(
                        default=False,
                        verbose_name="Analiza učinka na osebne podatke opravljena",
                    ),
                ),
                (
                    "personal_data_analysis_comments",
                    models.TextField(
                        blank=True,
                        verbose_name="Komentarji analize učinka na osebne podatke",
                    ),
                ),
                (
                    "public_procurement",
                    models.BooleanField(
                        default=False,
                        help_text="Ali je bil vnos predmet javnega naročila?",
                        verbose_name="Javno naročilo",
                    ),
                ),
                (
                    "public_procurement_number",
                    models.CharField(
                        blank=True,
                        help_text="Številka javnega naročila na portalu javnih naročil (PJN), če je predmet javnega naročila",
                        max_length=50,
                        null=True,
                        verbose_name="Številka objave na PJN",
                    ),
                ),
                (
                    "public_procurement_number_eu",
                    models.CharField(
                        blank=True,
                        help_text="Številka javnega naročila na portalu TED (tenders electronic daily), če je predmet javnega naročila",
                        max_length=50,
                        null=True,
                        verbose_name="Številka objave na TED",
                    ),
                ),
                (
                    "public_procurement_date",
                    models.DateField(
                        blank=True,
                        help_text="Datum objave javnega naročila, če je predmet javnega naročila",
                        null=True,
                        verbose_name="Datum objave javnega naročila",
                    ),
                ),
                (
                    "contracting_institution",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="home.TaggedContractingInstitution",
                        to="home.InstitutionTag",
                        verbose_name="Naročnik",
                    ),
                ),
                (
                    "institution",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="home.TaggedInstitution",
                        to="home.InstitutionTag",
                        verbose_name="Institucija",
                    ),
                ),
                (
                    "registry_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registryentryinstitutiondata",
                        to="home.registryentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podatki povezani s specifično institucijo pri vnosu v register",
                "verbose_name_plural": "Podatki povezani s specifičnimi institucijami pri vnosih v register",
            },
        ),
    ]
