# Generated by Django 5.2.8 on 2025-11-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_migrate_institution_data_to_related_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registryentryinstitutiondata",
            options={
                "verbose_name": "Podatki institucije pri vnosu",
                "verbose_name_plural": "Podatki institucij pri vnosih",
            },
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="contracting_institution",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="cost_comment",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="human_rights_analysis_comments",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="human_rights_analysis_done",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="institutions",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="license_duration",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="license_duration_comment",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="personal_data_analysis_comments",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="personal_data_analysis_done",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="public_procurement",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="public_procurement_date",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="public_procurement_number",
        ),
        migrations.RemoveField(
            model_name="registryentry",
            name="public_procurement_number_eu",
        ),
    ]
